// <auto-generated />
namespace Imaftec.Gps.Monitor.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class entidade_dispositivo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entidade_dispositivo));
        
        string IMigrationMetadata.Id
        {
            get { return "201509280037269_entidade_dispositivo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
